### ISSUE TITLE
Question about the reference?

### ISSUE THREAD

**Issue by zhangjy859** [arangrhie/T2T-HG002Y#4]
Hi, 
I noted your accessibility mask process script reference including  three different reference: 
```
chm13v2.0.fasta
chm13v2.0.XX.fasta
chm13v2.0.XY.fasta
```
I am not sure whats the source of `chm13v2.0.XX.fasta` and `chm13v2.0.XY.fasta`, Could you please clarify this?

Regrads

Zhang

**Comment by dtaylo95** [comment]
Hi @zhangjy859,

These are the references that were initially used for alignment and variant calling. They will be available through the `AnVIL_T2T_CHRY` AnVIL Workspace once it is made publicly available (hopefully within the next few days).

`chm13v2.0.fasta` is the unmasked reference. `chm13v2.0.XX.fasta` and `chm13v2.0.XY.fasta` are the two sex chromosome complement (SCC)-aware references that were actually used for alignment. The XX reference has the entire Y chromosome masked, while the XY reference has only the Y-PARs masked.

**Comment by zhangjy859** [comment]
Hi @dtaylo95, 

Thanks for your reply, sorry for more question, I noted your mentioned that 
```
Compare observed coverage to median autosomal coverage
...
```
in `readme.md`

I am trying to view your code, in my understanding, in this step, all chromosome including sex chromosomes but not only autosomal been considered, in fact (see [coverage_mask_wrapper.sh](https://github.com/arangrhie/T2T-HG002Y/blob/main/accessibility_masks/code/coverage_mask_wrapper.sh), Is it right?

Regrads

Zhang

**Comment by dtaylo95** [comment]
@zhangjy859, if I'm understanding your question correctly: yes, we generate the depth mask for every chromosome (i.e. both autosomal and sex chromosomes). But this mask is based on the median coverage across ONLY the autosomes (which is stored in the `median_cov.txt` file we generated earlier in the pipeline).

I hope this answers your question!

**Comment by zhangjy859** [comment]
Hi @dtaylo95,

I understand. Thank you for your answer. Its my problem, I seem to have confused some content while reading your script. Thank you for your clarification. I will close this issue.

Regrads

Zhang
